### ISSUE TITLE
Build instructions, CLI, etc.?

### ISSUE THREAD

**Issue by davisjam** [fmselab/mutrex#1]
Hello,

I would like to use this tool as a CLI.
Do you have build instructions, a usage message, etc.?

Thanks!

**Comment by garganti** [comment]
I have built an eclipse project for a cli version. Read the readme file. It is very simple to use (yet not very powerful). Please take a look and let us know if you need a more sophisticated version.

**Comment by davisjam** [comment]
Thank you! I will give it a try.
